myriadrf/LimeSuite

SoapyLMS7/Settings.cpp
Integrated the LMS API CalibrateTx/CalibrateRx functions into the LimeSDR Soapy wrapper
Example usage (quick_test.py):
```
#Perform calibration using LMS C++ API CalibrateTx/CalibrateRx functions:
streamBoardSDR.writeSetting("CALIBRATE_TX", "10");
streamBoardSDR.writeSetting("CALIBRATE_RX", "10");
streamBoardSDR.writeSetting("CALIBRATE_TX_EXTLOOPBACK", "10");
streamBoardSDR.writeSetting("CALIBRATE_RX_EXTLOOPBACK", "10");
```
=> added LMS API CalibrateRx/Tx support to Soapy wrapper

SoapyLMS7/Streaming.cpp
setupStream() was setting up no channels when called with the default
argument (empty list), but the SoapySDR device API specifies that an
empty channel list should result in automatic setup.
=> SoapyLMS7: add channel 0 as default to setupStream()

SoapyLMS7/LimeSuiteCalibrate.py
When no options are provided, LimeSuiteCalibrate fails with an exception traceback:
```
Traceback (most recent call last):
File "/usr/bin/LimeSuiteCalibrate", line 378, in <module>
if __name__ == '__main__': main()
File "/usr/bin/LimeSuiteCalibrate", line 375, in main
validate = options.validate,
File "/usr/bin/LimeSuiteCalibrate", line 312, in LimeSuiteCalibrate
if freqStart is None: raise Exception("No start frequency specified")
Exception: No start frequency specified
```
This is a little unexpected, so this commit marks the `freqStart` and `freqStop` options as required, to trigger an error with the program usage:
```
usage: LimeSuiteCalibrate.py [-h] [--args ARGS] --freqStart FREQSTART
--freqStop FREQSTOP [--freqStep FREQSTEP]
[--dumpDir DUMPDIR] [--validate]
LimeSuiteCalibrate.py: …
```
=> Improve LimeSuiteCalibrate options handling

.travis.yml
This is a larger project and 8 separate build combinations didnt seem necessary, and some builds were failing to clone the repo (possible throttling?). Reduce the matrix to practical combinations. Release mode on osx+clang, and linux+gcc. Doing this as a PR to test the changes.
=> travis - reduce the size of the test matrix

src/lms7002m/LMS7002M_parameters.h
Can't compile C language,error unknown type name ‘LMS7Parameter’
> jiangwei@ubuntu:~/test$ gcc test.c -std=c89
In file included from /usr/local/include/lime/LimeSuite.h:26:0,
from test.c:1:
/usr/local/include/lime/LMS7002M_parameters.h:27:26: error: unknown type name ‘LMS7Parameter’
int LMS7ParameterCompare(LMS7Parameter a,LMS7Parameter b);
^
/usr/local/include/lime/LMS7002M_parameters.h:27:42: error: unknown type name ‘LMS7Parameter’
int LMS7ParameterCompare(LMS7Parameter a,LMS7Parameter b);
^
=> fix unknown type name error in c

src/ConnectionSTREAM/ConnectionSTREAM.cpp, src/ConnectionSTREAM/ConnectionSTREAMEntry.cpp, src/Connection_uLimeSDR/Connection_uLimeSDREntry.cpp
Not sure why the libusb_free_device_list call would only run if no
devices are found at all (which never happens on machines with USB
controllers because of root hubs). No references are held to devices
from the list, so it is safe to free the list and unref its devices
after finishing the loop.
This avoids a device leak list when probing for devices with SoapySDR,
which occurred even when no LimeSDR devices were present.
=> Properly free libusb device lists

src/ConnectionSTREAM/ConnectionSTREAMing.cpp, src/ConnectionXillybus/ConnectionXillybusing.cpp, src/Connection_uLimeSDR/Connection_uLimeSDRing.cpp, src/lms7suiteApp.cpp
Unless the intention was to have a timestamp of 0 it seems okay to remove the 3 and then move the other one into the ifdef.
=> Quiet compile warnings by removing unused variables.

SoapyLMS7/Settings.cpp, SoapyLMS7/SoapyLMS7.h
Minor change to remove a hacky const_cast. Doing this as a PR to check that mutable would compile on the CI builds.
=> soapy lms7 - make mutex mutable for const methods

src/fftviewer_wxgui/fftviewer_wxgui.cpp, src/fftviewer_wxgui/fftviewer_wxgui.fbp, src/lms7002_wxgui/lms7002_pnlRBB_view.cpp, src/lms7002_wxgui/lms7002_pnlRxTSP_view.cpp, src/lms7002_wxgui/lms7002_pnlTxTSP_view.cpp, src/lms7002_wxgui/lms7002_wxgui.cpp
- Fix two size issues for labels where size was explicitly stated instead of automatic size setup
Before (example): 
After (example): 
- Add space between units (MHz, dBFS, V etc.) for consistency in a lot of panels
Before (example): 
After (example): 
Note: While working on commit 1109427 I noticed some weird behaviour in the `TxTSP` and `RxTSP` panels: If you visit these panels after the first time, some labels get set to a different value than before (note the `Angle` column changing to `PHO`). Also if you switch between the `FCW` and `PHO` mode, some labels in the `RxTSP` panel get swapped whereas in the `TxTSP` panel they stay the same. I have no idea what the default behaviour should be...
=> Fix minor gui issues

src/fftviewer_wxgui/fftviewer_frFFTviewer.cpp
This commit fixes two bugs in the capture function of the FFTviewer.
Previously, the capture buffer was always [written starting at the address of the first sample](https://github.com/myriadrf/LimeSuite/compare/master...milestone12:master#diff-19366fd8df444a99788a9ae689483f14L440) in every loop iteration. Thus, only the first "segment" of the buffer would contain samples whereas the rest of it would be just '0':
An [array of counter variables has been introduced](https://github.com/myriadrf/LimeSuite/compare/master...milestone12:master#diff-19366fd8df444a99788a9ae689483f14R367) in order to keep track of the number of written samples and to [set the initial address for the memcpy operation](https://github.com/myriadrf/LimeSuite/compare/master...milestone12:master#diff-19366fd8df444a99788a9a …
=> FFTviewer bug fix: write full capture buffer & out-of-bounds protection

SoapyLMS7/SoapyLMS7.h, SoapyLMS7/Streaming.cpp, src/ConnectionSTREAM/ConnectionSTREAMing.cpp
The limesuite streams are independent and do not stay aligned in the presence of overflow. This change adds stream alignment to soapy lms readStream(). This ensures that all N channels are aligned to the same timestamp and contiguous when the readStream() call returns.
SoapyLMS users could also manually open and read from each stream individually and perform alignment outside of the SoapyLMS layer. This just implements alignment for the multiple channel configuration case -- which was the intention.
* no changes to limesuite api
* only soapylms layer changed
* resolves #141
* fyi @ccsh23
=> Soapylms mimo align fix

SoapyLMS7/Settings.cpp
SoapySDR::ticksToTimeNs divides by rate and needs sample rate set beforehand
=> fix floating point exception in SoapyLMS7::getHardwareTime

SoapyLMS7/BasicStreamTests.py
Hi,
I've added the support of LimeSDR-Mini in SoapyLMS7/BasicStreamTests.py by detecting the number of channels.
It's not a big deal but I share it.
=> Add the support of LimeSDR-Mini in LSM7 basic stream test script

LimeUtil/LimeUtil.cpp
Removes that ugly terminal cursor lag
=> limeutil: flush the output when downloading

Changelog.txt, src/lms7002m/LMS7002M.cpp, src/lms7002m/LMS7002M_filtersCalibration.cpp, src/lms7002m/LMS7002M_gainCalibrations.cpp
Using MAC means that the indexes were 1 and 2 for the two element array opt_gain_tbb.
Using GetActiveChannelIndex() provides 0 and 1 for an array index for ChA and ChB.
=> Fix index lookup for opt_gain_tbb cache (ChB out of bounds)

cmake/DownloadImages.cmake
the download page changed from plain directory listing to a more
complex page, with css and so on. Therefore we need a more restrictive
regex to get just image files.
patch done by @michaelld
=> fix images download regex

src/RFSpark/RFSpark_wxgui.cpp, src/lms7002_wxgui/pnlBoardControls.cpp
GCC was warning about unreachable cases, so I corrected the arg type to match the value being used in the only instance of this function.
I also removed the definition of this function from `RFSpark_wxgui.cpp`, since it was overriding the static function definition in `pnlBoardControls.cpp`, where it was actually being used.
=> Fix power2unitsString compiler warnings

src/API/LimeSDR_mini.cpp
This fixes the following warning:
```
src/API/LimeSDR_mini.cpp: In member function ‘virtual int lime::LMS7_LimeSDR_mini::Calibrate(bool, unsigned int, double, unsigned int)’:
src/API/LimeSDR_mini.cpp:163:44: warning: comparison between ‘enum lime::LMS7002M::PathRFE’ and ‘enum<unnamed>’ [-Wenum-compare]
wr_val |= lms_list[0]->GetPathRFE() == LMS_PATH_LNAW ?  0x100 : 0x200;
^~~~~~~~~~~~~
```
This still worked because the enums it was comparing between happened to have the same value for the LNAW path, but comparing raw values between enums is generally not a good idea because in doing so you lose all the benefits of type-checking.
=> Fix comparison between mismatched enums

src/lime/LimeSuite.h
This log level is available in Logger.hpp but missing in the C public
API.
=> LimeSuite.h: Introduce define LMS_LOG_CRITICAL

QuickTest/TestGUI.cpp
Without this change, [scan-build](https://clang-analyzer.llvm.org/scan-build.html) warns that the address of stack variable `gui` is being stored in a global variable.
Practically speaking, this doesn't really matter much since `main()` is only ever called once, but it's an easy fix and there's really no reason not to do it.
=> long_options doesn't need to be static

src/ConnectionFX3/ConnectionFX3.cpp
Workaround for Linux kernel bug for USB 3 AMD host controllers -- myriadrf/LimeSuite#287
=> Workaround for kernel bug with USB 3 AMD host controllers

src/oglGraph/OpenGLGraph.cpp
fix openGL grpah size with Retina (HighDPi) display.
Maybe we should fix the font size also; particulary in the axis but it is not enough to change this
```
diff --git a/src/oglGraph/OpenGLGraph.cpp b/src/oglGraph/OpenGLGraph.cpp
index d1d3cab6..57f02bb2 100644
--- a/src/oglGraph/OpenGLGraph.cpp
+++ b/src/oglGraph/OpenGLGraph.cpp
@@ -769,7 +769,7 @@ GLvoid OpenGLGraph::glRenderText(float posx, float posy, float angle, float scal
//if font has been loaded
glEnable(GL_TEXTURE_2D);
if(m_font != NULL)
-            m_font->render_textWorldSpace(text, 0, 0, scale, rgba);
+            m_font->render_textWorldSpace(text, 0, 0, scale * GetContentScaleFactor(), rgba);
glPopMatrix();
glDisable(GL_TEXTURE_2D);
```
because we need to resize the free space on the graph borders.
=> oglGraph: fix size with Retina display

SoapyLMS7/Settings.cpp
Currently, this SoapySDR module returns some fixed values as the sample rate range and only those two values as the list of sample rates.
This causes some issues with apps using SoapySDR to work with LimeSDR devices:
- Those using the range allow setting the sample rate to values over LimeSDR Mini specification and cause issues.
- Those using the list of sample rates only get 0.1 and 65 Msps values as is what the module says and for example in LimeSDR Mini 65 Msps is way higher than the 30.72 Msps specification. Also, you don't get more values you can use.
This PR attempts to fix this by getting device values calling to `LMS_GetSampleRateRange` and returning those in the case of the range function or creating some stepped values in between the min and max values.
In any case, if the …
=> Return the device actual supported sample rate in the SoapySDR module

src/lime/LimeSuite.h
Fixes a minor warning about the LMS_GetLibraryVersion() prototype in lime/LimeSuite.h
=> Minor fix LMS_GetLibraryVersion prototype

src/limeRFE/limeRFE_wxgui.cpp, src/limeRFE/limeRFE_wxgui.h
wxString may not be implicitly convertible to const char*, so add an
overload.
=> Allow compilation with wxWidgets STL build

src/examples/dualRXTX.cpp
At first glance it is unclear where is the error in the comments or in
the code. Until the real intention is not known it looks like an error
in the code where 1.2GHz is used instead of 1.0GHz.
The desired behavior can be found in the documentation (Pg. 18 of the
docs/lms7_api_quick_start_guide.pdf, para: 3.3.2 Device configuration:
"The Rx frequency for both channels is set to 1 GHz while Tx frequency
is set to 1.2 GHz."
=> Fix a wrong frequency value in comments

src/examples/limeRFE_USB_example.cpp
=> Fix a trivial copy-paste typo in comments.

src/protocols/Streamer.cpp
Fix NULL-pointer dereference in the `Read` member function. This
function is protected from this problem in case of and indirect call
via `LMS_RecvStream` function, but in case of direct call the problem
may occur.
Note that the `Write` function isn't fixed!
Test: create a `StreamChannel` instance, call the `Read` function and
=> Protocols: fix null pointer dereference in the Read member function

src/protocols/LMS64CProtocol.h
Just a minor cosmetic change.
The patch provides the following changes:
- add the `override` specifier for the overridden functions;
- remove the `virtual` specifier for the overridden functions.
=> Add the override specifier when it possible

src/protocols/LMS64CProtocol.cpp
Just a minor cosmetic fix.
P.S. moreover the ```readLen``` should be ```int``` instead of ```long```.
=> Remove redundant temporary variable.

src/ConnectionFTDI/ConnectionFT601.cpp, src/ConnectionFX3/ConnectionFX3.cpp
The current implementation tries to handle spurious wakeups manually,
but the standard library provides the overloaded version of the
`std::condition_variable::wait_for` that can be used to ignore spurious
awakenings.
Also, the current implementation has a minor logical error: in the case of
false wakeup, the next sleep timeout should be reduced by the time that
was spent on previous waiting.
For details see:
- https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for ;
- https://en.cppreference.com/w/cpp/thread/condition_variable/wait .
=> Improve spurious wakeup handling in USB transfer waiting

src/ConnectionSTREAM_UNITE/ConnectionSTREAM_UNITE.cpp
"ErrorReporting.h" does not seem to be a part of the code anymore.
Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>
=> Fixed Stream Unite headers build problem.

LimeUtil/LimeUtil.cpp
This allows command line enabling of the external reference port REF_CLK_IN on LimeSDR-USB in a similar manner as the ADF4002 dialog in LimeSuite. Seems useful for enabling a GPSDO on headless deployments. Also contains code to query and display the current lock state (0/1).
=> Add LimeUtil option to set and enable external reference on ADF4002

CMakeLists.txt
When LimeSuite as a dependency for a project using add_subdirectory, the source dir differs.
This change ensures that CMake looks for modules in the right folder.
=> Fix module dir

SoapyLMS7/Streaming.cpp
There is already code to parse the option, but it was not declared in the list of options the driver supports.
The limited size of USB transfers is significantly affecting performance on a RaspberryPi 4 running 64 bit Ubuntu 20.04. Without increasing the size I'm regularly seeing samples being lost (gr-soapy is not reporting this because it does not call `readStreamStatus()`).
=> soapy: enable access to the latency parameter

CMakeLists.txt
Some of architectures such as riscv64 don't support "-march=native" yet, so this flag shouldn't be added by default on unsupported architectures.
=> Only enable march native on supported architectures

SoapyLMS7/Settings.cpp, SoapyLMS7/SoapyLMS7.h
This PR facilitates setting of external clock reference freq. from Soapy.
=> Allow settings external reference clock from Soapy

src/oglGraph/OpenGLGraph.cpp
This fixes interaction with OpenGL graphs used, for example, in the FFT View module of the LimeSuiteGUI. This includes:
- Zoom in by mouse-drag, where the zoom border used to be using wrong coordinates.
- Panning, which used to happen at half the mouse speed.
- Adding markers, which used to be added at a wrong location.
The issue was happening on the macOS with Retina displays.
=> Fix OpenGL graph on Retina displays

src/utilities_gui/pnlMiniLog.cpp
When the Lime Suite GUI is used on a macOS which is default to the dark mode the information logged into the log window was hard to read: it was defaulting to the black foreground.
The behavior now matched when no SetDefaultStyle() used at all: the light theme will use black text, and the dark theme will use the white color.
The limitation this change does not address is the update of the colors in the log window when the theme is changed between dark ans light while the LimeSuiteGUI is running.
=> Fix hard-to-read log text on dark mode themes

debian/control
Make the package build on debian bookworm (12).
=> debian/control: update libwxgtk dep for bookworm

CMakeLists.txt
The code before this change did not provide any help text to the option, which made it so CMake defined an option with TRUE as description, and default value of OFF as per the CMake documentation:
https://cmake.org/cmake/help/latest/command/option.html
This can be verified by checking on the CMakeCache.txt:
```
//TRUE
CMAKE_AUTOSET_INSTALL_RPATH:BOOL=OFF
```
This option was introduced in the commit 416510492d4 with an intent to disable the automatic RPATH logic for Debian packing.
This change merely sanitizes the CMake usage, making it less confusing for a reader: it seemed that the option was set to TRUE while the confusingly it was set to OFF. There is no expected change in behavior with this change.
=> Fix specification of CMAKE_AUTOSET_INSTALL_RPATH CMake option

src/lms7002m_mcu/MCU_File.cpp
Without the change build on `gcc-13` fails as:
/build/source/src/lms7002m_mcu/MCU_File.cpp:340:21: error: 'uint8_t' was not declared in this scope
340 |                     uint8_t i = 0;
|                     ^~~~~~~
/build/source/src/lms7002m_mcu/MCU_File.cpp:4:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
3 | #include <iostream>
+++ |+#include <cstdint>
=> lms7002m_mcu: fix `gcc-13` build (missing <stdint.h>)

src/utilities_gui/pnlMiniLog.cpp
After a warning error has been logged in the LimeSuiteGUI all the following messages had an yellow background, which is an unexpected behavior.
Apparently it was caused by the previous fix in the area which made it so the text color is restored to its default value. Somehow it had an effect on the background color behavior: as if there is some implicit behavior when neither of the foreground and background are set in the style when it is set as default to the message field.
It is hard to tell now if this was an oversight in the previous fix, or is it something changed in the wxWidgets library. In any case the logging behavior has been verified once again on both Dark and Light themes on macOS.
=> Fix warning background "sticky" behavior

src/examples/singleRX.cpp
The issue this commit fixes is that running singleRX example does not show any samples streaming, and logs shows: RX data rate: 0 MB/s.
The fix follows the initialization order in basicRX.cpp where the TX channel is enabled alongside with the RX channel right after the LMS_Init(). With this fix running singleRX example shows samples streamed: RX data rate: 32.1454 MB/s.
This is a bit counter-intuitive API from developers perspective (as in, intuitively question is why TX channel is needed for RX-only application). So it does feel like that perhaps the fix needs to be done somewhere deeper in the driver or in gateware to increase clarity of API. However, that'd be a deeper change, if it happens. In any case, until such possible change the proposal is to fix the issue in the same way as it …
=> Fix singleRX example to work correctly with LimeSDR Mini V2

CMakeLists.txt
Hello!
I recently upgraded to a new MacBook Pro. Since I planned on using my LimeSDR in combination with the new laptop I had to compile LimeSuite from source since homebrew no longer offers prebuilt versions.
Everything compiled fine but running certain executables (for example LimeUtil) resulted in errors like this:
```
dyld[22779]: Library not loaded: @rpath/libLimeSuite.23.11-1.dylib
Referenced from: <49EAFDEF-E479-36A4-8FEC-3E2A8E368C49> /usr/local/bin/LimeUtil
Reason: no LC_RPATH's found
zsh: abort      LimeUtil
```
Updating the main CMakeLists file with the content of this pull request fixes the issue and everything runs fine again.
It appears to be an issue with recent macOS versions as I could reproduce it on macOS 13 (Intel CPU) and macOS 14 (M3 Pro CPU). In both cases it is now …
=> Update CMakeList for modern macOS versions

SoapyLMS7/Settings.cpp, SoapyLMS7/Streaming.cpp, src/tests/include/limesuite/CommsMock.h, src/tests/protocols/LMS64CProtocol/CustomParameterReadTest.cpp, src/tests/protocols/LMS64CProtocol/CustomParameterWriteTest.cpp, src/tests/protocols/LMS64CProtocol/DeviceResetTest.cpp, src/tests/protocols/LMS64CProtocol/FPGA_SPITest.cpp, src/tests/protocols/LMS64CProtocol/GPIODirReadTest.cpp, src/tests/protocols/LMS64CProtocol/GPIODirWriteTest.cpp, src/tests/protocols/LMS64CProtocol/GPIOReadTest.cpp, src/tests/protocols/LMS64CProtocol/GPIOWriteTest.cpp, src/tests/protocols/LMS64CProtocol/GetFirmwareInfoTest.cpp, src/tests/protocols/LMS64CProtocol/LMS7002M_SPITest.cpp
- Compilation issues in the SoapySDR module.
- Compilation issues in the tests.
=> Fix compilation errors in the SoapySDR module and tests
